Air super build (#989)

diff --git a/programming_examples/passthrough/passthrough_kernel/Makefile b/programming_examples/passthrough/passthrough_kernel/Makefile
--- a/programming_examples/passthrough/passthrough_kernel/Makefile
+++ b/programming_examples/passthrough/passthrough_kernel/Makefile
@@ -2,9 +2,16 @@
 # SPDX-License-Identifier: MIT
 srcdir := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
 
-targetname := $(shell basename ${srcdir})
+# Determine build dir based on whether PEANO_INSTALL_DIR is set
+ifdef PEANO_INSTALL_DIR
+  BUILD_DIR := build_peano
+else
+  BUILD_DIR := build_chess
+endif
 
-include ${srcdir}/../../makefile-common
+AIEOPT_DIR = $(shell realpath $(dir $(shell which aie-opt))/..)
+WARNING_FLAGS = -Wno-parentheses -Wno-attributes -Wno-macro-redefined -Wno-empty-body
+PEANOWRAP2_FLAGS = -O2 -std=c++20 --target=aie2-none-unknown-elf ${WARNING_FLAGS} -DNDEBUG -I ${AIEOPT_DIR}/include
 
 targetname = passThroughKernel
 
@@ -13,13 +20,27 @@ all: run
 print:
 	${powershell} python3 ${srcdir}/passthrough_kernel.py -p
 
-build/passThrough.cc.o: ${srcdir}/passThrough.cc
-	mkdir -p build
-	cd build && xchesscc_wrapper ${CHESSCCWRAP2_FLAGS} -DBIT_WIDTH=8 -c $< -o ${@F}
-
-run: build/passThrough.cc.o
-	mkdir -p build
-	cd build && ${powershell} python3 ${srcdir}/passthrough_kernel.py
+run: compile-kernel
+	PEANO_INSTALL_DIR=$(PEANO_INSTALL_DIR) cd $(BUILD_DIR) && ${powershell} python3 ${srcdir}/passthrough_kernel.py
+	
+compile-kernel:
+	mkdir -p $(BUILD_DIR)
+	@if [ -n "$(PEANO_INSTALL_DIR)" ]; then \
+		echo "Detected PEANO_INSTALL_DIR from environment: $(PEANO_INSTALL_DIR)"; \
+		if [ -x "$(PEANO_INSTALL_DIR)/bin/clang++" ]; then \
+			echo "Using clang++ from PEANO_INSTALL_DIR=$(PEANO_INSTALL_DIR)"; \
+			$(PEANO_INSTALL_DIR)/bin/clang++ ${PEANOWRAP2_FLAGS} -DBIT_WIDTH=8 -c ${srcdir}/passThrough.cc -o $(BUILD_DIR)/passThrough.cc.o; \
+		else \
+			echo "Error: invalid PEANO_INSTALL_DIR, clang++ not found."; \
+			exit 1; \
+		fi; \
+	elif command -v xchesscc_wrapper >/dev/null 2>&1; then \
+		echo "Using xchesscc_wrapper from PATH"; \
+		cd $(BUILD_DIR) && ${powershell} xchesscc_wrapper aie2 -c ${srcdir}/passThrough.cc -o passThrough.cc.o; \
+	else \
+		echo "Error: Neither PEANO_INSTALL_DIR nor xchesscc_wrapper found."; \
+		exit 1; \
+	fi
 
 clean:
-	rm -rf build __pycache__
+	rm -rf $(BUILD_DIR) __pycache__
